---
# tasks file for EtcdHaproxyServer
- name: copy "etcd config file"
  copy:
    src: etcd
    dest: /etc/default
- name: create dcs directory "cluster key storage"
  file:
    path: /data/etcd
    state: directory
    owner: etcd
    group: etcd

- name: copy "haproxy config file"
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/
